### ISSUE TITLE
Library fails reading long responses , e.g. from the new NRIQSTN command.

### ISSUE THREAD

**Issue by jdla** [miracle2k/onkyo-eiscp#46]
Dear,

I was using this library for controlling my TX8150. (Async mode)
All goes well, except for the NRIQSTN command that gives a long response ( > 7000 bytes ) on which the library fails.

The eISCP.get goes wrong. 
It does 

`message = self.command_socket.recv(header.data_size)`

This goes well for all the short responses ( shorter than an ethernet frame )
However for this 7000 bytes response len(message) might be less than header.data_size.
Parsing further down the road goes wrong then ( assertion on EOF fails ).

The quick hack I made, but my skills in the area are rusty, goes as follows

    message = self.command_socket.recv(header.data_size)
    while len(message) != header.data_size :
		ready = select.select([self.command_socket], [], [], 0.5 )
		if not ready[0] :
			break
		ToRead = header.data_size - len(message)
		message = message + self.command_socket.recv(ToRead)

**Comment by nickovs** [comment]
I've just fallen foul of this problem too and tracked it down to the same problem. From my investigation it seems that XML responses are generated fairly slowly by the receiver which means that the client is likely to try to read the data before it has all arrived and as a result gets an incomplete result. This bug is a problem for me since the NRI command seems to be the only way to detect if the volume control expects 1db steps from 0 to 80 or 0.5db steps from 0 to 160.

**Comment by nickovs** [comment]
I've submitted a pull request to fix this bug. Hopefully it will be accepted.
