### ISSUE TITLE
Sending command to select 'TV' source results in selecting 'CD' source

### ISSUE THREAD

**Issue by joe248** [miracle2k/onkyo-eiscp#60]
I have an Onkyo TX-NR646.  Using this library within [Home Assistant](https://home-assistant.io).  When I select the TV source using the library, my receiver instead selects the CD source.  Looking at [commands.py](https://github.com/miracle2k/onkyo-eiscp/blob/3768523e7f296b1a88441b83256fbb9457e4a2ce/eiscp/commands.py#L3100), it's sending a value of 23 for the TV source when it should be sending 12 (see [here](https://github.com/miracle2k/onkyo-eiscp/blob/62c4b8fdc3c4ab537805e087ccadb56bf6433c1b/eiscp-commands.yaml#L3529)).  I believe this is happening due to the multiple names for value 23 [here](https://github.com/miracle2k/onkyo-eiscp/blob/62c4b8fdc3c4ab537805e087ccadb56bf6433c1b/eiscp-commands.yaml#L3545).  I'm not sure what the fix is, though.  Perhaps `name: [cd, tv, cd]` should be changed to `name: [cd, tv/cd]`?

**Comment by jeromeloman** [comment]
you are right looks like the command should have been parse as: ('cd', 'tv'/cd') the doc says "sets CD    TV/CD"

It's hard to automate the command parser because some description are "CBL/SAT" which you want to split into "CBL", "SAT"..
older onkyo don't support TV and CD only "TV/CD" whereas 646 suppors TV and CD seperatly.

**Comment by Woetsel** [comment]
I have a TX-NR646 as well and I'm running into the same issue.
